name: Testing

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore spacebattle

      - name: Build
        run: dotnet build spacebattle --no-restore /p:ContinuousIntegrationBuild=true

      - name: Format
        run: dotnet format --verify-no-changes
        
      - name: UnitTest + Coverage
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults /p:CoverletOutputFormat=cobertura
